site_name: broker
site_description: A simple REST API for a broker
repo_url: https://github.com/TheLazzziest/broker-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/TheLazzziest">TheLazzziest</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
